### PR TITLE
Added Member.buzz to the list of sites

### PR DESCRIPTION
**Pull request by wyeack**

### CODE REVIEW

**Comment by Taritsyn** [comment]
Hello, William!

I did not find signs of using the Bundle Transformer on the Member.buzz site.

**Comment by wyeack** [comment]
Hey @Taritsyn - what sort of signs are you looking for?  It is an ASP.NET MVC application and we use Bundle Transformer for the following stuff:
- Transform all our SCSS files into CSS and bundle them into a bundle.
- Combine all of our JavaScript files into a bundle.
We use the ChakraCore engine and the YuiCssMinifier.  We are still working on getting JavaScript minification working.

Ultimately the scripts and styles are delivered through a CDN, the output of which you can see here:
https://resources.member.buzz/scripts
https://resources.member.buzz/styles

The direct origin of the output can be found here:
https://www.member.buzz/content/resources/scripts
https://www.member.buzz/content/resources/styles

**Comment by wyeack** [comment]
p.s. I'm with Member.buzz so I definitely know we use and love your library!
https://www.member.buzz/about/team

**Comment by Taritsyn** [comment]
Hello, William!

OK. It just seemed strange that JS-code was not minified.

**Pull request merged**
